version: '3'
services:
  react-docker:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      # - "/home/bijay/Documents/Work Area/docker-react-app/frontend:/home/node/app"
      - .:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
